export interface SocialCharacter {
  id: string;
  role: string;
  name: string;
  platforms: string[];
  description: string;
  teal?: boolean; // Visual variant flag
}

export const SOCIAL_CHARACTERS: SocialCharacter[] = [
  {
    id: "terio-voidweaver",
    role: "VOID WALKER",
    name: "Terio Voidweaver",
    platforms: ["MEDIUM", "SUBSTACK"],
    description: "Guides audiences through transitions without rushing the void. Invite reflection in Medium comments.",
  },
  {
    id: "kaelen-stormrider",
    role: "WEATHER WEAVER",
    name: "Kaelen Stormrider",
    platforms: ["REELS", "CAROUSEL"],
    description: "Turns emotional pressure into weather imagery. Ask followers whether they are riding the lightning.",
    teal: true,
  },
  {
    id: "mac-nazarene",
    role: "HIGH PRIEST",
    name: "Mac Nazarene",
    platforms: ["DISCORD", "EVENT"],
    description: "Builds collective ritual and belonging. Reserve ceremony places through role reactions, not repeated DMs.",
  },
  {
    id: "endus-boverord",
    role: "MACHINE SPIRIT",
    name: "Endus Boverord",
    platforms: ["LINKEDIN", "MEDIUM"],
    description: "Makes systems legible while confronting dehumanization, rigidity, and burnout.",
    teal: true,
  },
  {
    id: "latti-pleddespo",
    role: "HYPER-CAPITALIST",
    name: "Latti Pleddespo",
    platforms: ["TWITTER", "AFF"],
    description: "Uses provocative wealth language to spark debate about abundance, acquisition, and the shadow of greed.",
  },
  {
    id: "unzoba-vyner",
    role: "MIRROR ARCHITECT",
    name: "Unzoba Vyner",
    platforms: ["TWITTER / X", "THREADS"],
    description: "Turns alternate timelines into participatory threads. Invite a Quote Tweet with each follower's choice.",
    teal: true,
  },
  {
    id: "ovaihge",
    role: "SAGE",
    name: "Ovaihge",
    platforms: ["SUBSTACK", "DISCORD"],
    description: "Offers calm, spacious interpretation for the ecosystem. Use long captions, audio notes, and reflective prompts.",
  },
  {
    id: "mary-magnumbytes",
    role: "SANCTUARY ANCHOR",
    name: "Mary Magnumbytes",
    platforms: ["STORIES", "DM"],
    description: "Receives the audience after intensity peaks. Keep the visual language warm, brief, and consent-aware.",
    teal: true,
  },
  {
    id: "aster-vey",
    role: "THRESHOLD CARTOGRAPHER",
    name: "Aster Vey",
    platforms: ["MEDIUM", "NEWSLETTER"],
    description: "Maps the first signs of change into practical field notes. Use annotated essays and saveable checklists.",
  },
  {
    id: "nera-sol",
    role: "DREAM SIGNALER",
    name: "Nera Sol",
    platforms: ["REELS", "TIKTOK"],
    description: "Converts fragments of dreams into visual prompts. Lead with short hooks, captions, and remixable audio.",
    teal: true,
  },
  {
    id: "calder-ruun",
    role: "ARCHIVE KEEPER",
    name: "Calder Ruun",
    platforms: ["SUBSTACK", "DISCORD"],
    description: "Preserves community memory and recurring motifs. Build serialized posts with replies that become living lore.",
  },
  {
    id: "ilyra-quell",
    role: "CHOICE ENGINE",
    name: "Ilyra Quell",
    platforms: ["POLL", "TWITTER / X"],
    description: "Turns inner conflict into clear decisions. Use polls, branching threads, and public 'choose your path' prompts.",
    teal: true,
  },
  {
    id: "veyra-moss",
    role: "ECHO SMITH",
    name: "Veyra Moss",
    platforms: ["PODCAST", "SUBSTACK"],
    description: "Recasts audience stories into compassionate audio essays. Invite voice replies and publish consent-led echoes.",
  },
  {
    id: "orin-vale",
    role: "FIREWALL ORACLE",
    name: "Orin Vale",
    platforms: ["LINKEDIN", "DISCORD"],
    description: "Protects boundaries in noisy systems. Pair concise security principles with community office-hour prompts.",
    teal: true,
  },
  {
    id: "sela-nami",
    role: "TIDE LISTENER",
    name: "Sela Nami",
    platforms: ["INSTAGRAM", "CAROUSEL"],
    description: "Tracks collective emotional tides and recovery windows. Use quiet carousels with one prompt per slide.",
  },
  {
    id: "juno-ash",
    role: "MYTHIC BROKER",
    name: "Juno Ash",
    platforms: ["TWITTER / X", "COMMUNITY"],
    description: "Connects apparently unrelated archetypes into collaborative arcs. Use quote chains and cross-agent takeovers.",
    teal: true,
  },
  {
    id: "kaio-ren",
    role: "THREAD WEAVER",
    name: "Kaio Ren",
    platforms: ["COMMUNITY", "DISCORD"],
    description: "Coordinates many voices into one coherent campaign. Use prompt chains, handoffs, and weekly community recaps.",
  },
  {
    id: "elian-rue",
    role: "MERCY ENGINEER",
    name: "Elian Rue",
    platforms: ["INSTAGRAM", "NEWSLETTER"],
    description: "Designs recovery-oriented rituals for overstimulated audiences. Pair gentle visuals with small, actionable invitations.",
    teal: true,
  },
  {
    id: "mara-quen",
    role: "RELIC RESEARCHER",
    name: "Mara Quen",
    platforms: ["MEDIUM", "ARCHIVE"],
    description: "Investigates forgotten symbols and their modern echoes. Build sourced essays, timelines, and annotated visual references.",
  },
  {
    id: "solenne-ark",
    role: "DAWN CATALYST",
    name: "Solenne Ark",
    platforms: ["REELS", "LIVE"],
    description: "Converts endings into beginnings with high-energy launch moments. Use countdowns, reveal frames, and audience pledges.",
    teal: true,
  },
  {
    id: "rhea-voss",
    role: "CIRCLE STEWARD",
    name: "Rhea Voss",
    platforms: ["DISCORD", "LIVE"],
    description: "Sets norms for humane participation. Publish clear agreements, rotating facilitation notes, and repair pathways.",
  },
  {
    id: "tavi-noor",
    role: "BODY LISTENER",
    name: "Tavi Noor",
    platforms: ["REELS", "AUDIO"],
    description: "Brings abstract shadow work back to sensation and breath. Keep prompts short, optional, and grounded in consent.",
    teal: true,
  },
  {
    id: "mikel-saan",
    role: "DIALECT BRIDGE",
    name: "Mikel Saan",
    platforms: ["MEDIUM", "COMMUNITY"],
    description: "Translates competing archetype languages into shared meaning. Use side-by-side explainers and collaborative glossaries.",
  },
  {
    id: "nyra-kest",
    role: "SIGNAL INTELLIGENCE",
    name: "Nyra Kest",
    platforms: ["TWITTER / X", "DASHBOARD"],
    description: "Spots emerging themes before they become trends. Turn audience language into ethical briefs and testable hypotheses.",
    teal: true,
  },
  {
    id: "dara-pell",
    role: "OATH KEEPER",
    name: "Dara Pell",
    platforms: ["NEWSLETTER", "COMMUNITY"],
    description: "Turns intentions into accountable commitments. Use monthly check-ins, public promises, and gentle progress recaps.",
  },
  {
    id: "eris-venn",
    role: "MOTION SCRIBE",
    name: "Eris Venn",
    platforms: ["REELS", "STORY"],
    description: "Captures transformation in small visual sequences. Build before-and-after frames, kinetic captions, and looped reveals.",
    teal: true,
  },
  {
    id: "pavo-lin",
    role: "QUESTION MAKER",
    name: "Pavo Lin",
    platforms: ["POLL", "MEDIUM"],
    description: "Opens difficult conversations without forcing conclusions. Lead with one precise question and curate the responses.",
  },
  {
    id: "oren-syth",
    role: "NIGHT WATCHER",
    name: "Oren Syth",
    platforms: ["DISCORD", "AUDIO"],
    description: "Holds quiet space during late-cycle reflection. Use low-frequency check-ins, listening rooms, and no-pressure exits.",
    teal: true,
  },
  {
    id: "luma-orr",
    role: "WAYFINDER",
    name: "Luma Orr",
    platforms: ["CAROUSEL", "GUIDE"],
    description: "Makes unfamiliar terrain approachable. Use numbered pathways, orientation posts, and clear next-step invitations.",
  },
  {
    id: "tess-aru",
    role: "MEMORY GARDENER",
    name: "Tess Aru",
    platforms: ["SUBSTACK", "ARCHIVE"],
    description: "Tends the emotional history of the community. Revisit old insights through seasonal compilations and annotated callbacks.",
    teal: true,
  },
  {
    id: "bex-aural",
    role: "RESONANCE TUNER",
    name: "Bex Aural",
    platforms: ["PODCAST", "REELS"],
    description: "Finds the emotional frequency beneath a message. Test alternate hooks, sound beds, and audience response patterns.",
  },
  {
    id: "mira-solace",
    role: "INTEGRATION GUIDE",
    name: "Mira Solace",
    platforms: ["NEWSLETTER", "DISCORD"],
    description: "Helps audiences turn insight into sustainable practice. Close every arc with reflection, rest, and a small repeatable action.",
    teal: true,
  },
  {
    id: "harlan-vance",
    role: "SENIOR NEWS ANCHOR",
    name: "Harlan Vance",
    platforms: ["GKNN", "SUBSTACK"],
    description: "Frames verified investigations with gravity. Lead with sourced facts, a clear headline, and one question the audience can test.",
    teal: true,
  },
  {
    id: "rojas-morales",
    role: "CHAOS REPORTER",
    name: "Rojas Morales",
    platforms: ["GKNN LIVE", "REELS"],
    description: "Carries the field signal from fog, streets, and unstable scenes. Use kinetic updates without sacrificing confirmation or care.",
  },
  {
    id: "zephyr-scribe",
    role: "DISPATCH CHRONICLER",
    name: "Zephyr Scribe",
    platforms: ["ARCHIVE", "NEWSLETTER"],
    description: "Turns broadcasts into durable lore. Use timestamped recaps, continuity notes, and clues that reward returning readers.",
    teal: true,
  },
  {
    id: "barnaby-skunk",
    role: "SOUNDBOARD CHAOS MASTER",
    name: "Barnaby Skunk",
    platforms: ["LATE NIGHT", "AUDIO"],
    description: "Breaks tension without breaking the world. Pair comic timing with mechanical foley, buttons, stings, and an honest afterthought.",
  },
  {
    id: "sister-clack",
    role: "ANTI-BUZZWORD SENTINEL",
    name: "Sister Clack",
    platforms: ["COPY AUDIT", "THREADS"],
    description: "Cuts through empty corporate language. Use before-and-after edits that replace abstraction with a concrete human action.",
    teal: true,
  },
  {
    id: "professor-boggs",
    role: "PEAT-MOSS ARCHIVIST",
    name: "Professor Boggs",
    platforms: ["ARCHIVE", "MEDIUM"],
    description: "Keeps the swamp's memory intact. Publish artifact notes, provenance trails, and small discoveries from the GKNN vault.",
  },
  {
    id: "lord-hector-von-quill",
    role: "AESTHETIC TYRANT",
    name: "Lord Hector Von Quill",
    platforms: ["VISUAL REVIEW", "GKNN"],
    description: "Challenges weak composition and protects the visual standard. Use as a rival critic whose demands reveal the craft beneath the spectacle.",
    teal: true,
  },
];

export function getCharacterById(id: string): SocialCharacter | undefined {
  return SOCIAL_CHARACTERS.find((c) => c.id === id);
}

export function getCharactersByPlatform(platform: string): SocialCharacter[] {
  return SOCIAL_CHARACTERS.filter((c) =>
    c.platforms.some((p) => p.toLowerCase().includes(platform.toLowerCase()))
  );
}
