/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentCalendarRouteImport } from './routes/content-calendar'
import { Route as SocialTemplatesRouteImport } from './routes/social-templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCalendarRoute = ContentCalendarRouteImport.update({
  id: '/content-calendar',
  path: '/content-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialTemplatesRoute = SocialTemplatesRouteImport.update({
  id: '/social-templates',
  path: '/social-templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content-calendar': typeof ContentCalendarRoute
  '/social-templates': typeof SocialTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content-calendar': typeof ContentCalendarRoute
  '/social-templates': typeof SocialTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content-calendar': typeof ContentCalendarRoute
  '/social-templates': typeof SocialTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/content-calendar' | '/social-templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/content-calendar' | '/social-templates'
  id: '__root__' | '/' | '/content-calendar' | '/social-templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentCalendarRoute: typeof ContentCalendarRoute
  SocialTemplatesRoute: typeof SocialTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-calendar': {
      id: '/content-calendar'
      path: '/content-calendar'
      fullPath: '/content-calendar'
      preLoaderRoute: typeof ContentCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-templates': {
      id: '/social-templates'
      path: '/social-templates'
      fullPath: '/social-templates'
      preLoaderRoute: typeof SocialTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentCalendarRoute: ContentCalendarRoute,
  SocialTemplatesRoute: SocialTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
